# Site configuration
title: Airsonic
description: "Airsonic, a Free and Open Source community driven media server, providing ubiquitous access to your music."
url: "https://airsonic.github.io" # base hostname
baseurl: "" # subpath

# Build settings
markdown: kramdown
exclude:
  - Gemfile*
  - .git*
  - docs/.git*
  - README.md
  - LICENSE.txt
  - update_submodule.sh

# Github metadata
repository: airsonic/airsonic

# Vars
github_url: "https://github.com/airsonic/airsonic"
github_website_url: "https://github.com/airsonic/airsonic.github.io"
github_docs_url: "https://github.com/airsonic/documentation"
demo_url: ""
repo: "https://github.com/airsonic/airsonic/releases"

# Version bump
stable_version: "10.4.1"
subsonic_api_version: "1.15.0"
